//
//  Recovery.swift
//  21-DOT-DEV/swift-secp256k1
//
//  Copyright (c) 2026 Timechain Software Initiative, Inc.
//  Distributed under the MIT software license
//
//  See the accompanying file LICENSE for information
//

public import Foundation

#if canImport(libsecp256k1_zkp)
    import libsecp256k1_zkp
#elseif canImport(libsecp256k1)
    import libsecp256k1
#endif

#if Xcode || ENABLE_MODULE_RECOVERY

    // MARK: - secp256k1 + Recovery

    @available(macOS 10.15, iOS 13, watchOS 6, tvOS 13, macCatalyst 13, visionOS 1.0, *)
    public extension P256K {
        /// secp256k1 ECDSA recoverable signature namespace: sign with ``PrivateKey`` to produce an ``ECDSASignature`` that allows any verifier to recover the signer's ``PublicKey`` without prior knowledge.
        ///
        /// Recoverable signatures are 65 bytes (64-byte compact ECDSA signature + 1-byte recovery ID).
        /// They are produced by `secp256k1_ecdsa_sign_recoverable` and allow the signing public key
        /// to be recovered via `secp256k1_ecdsa_recover` given only the message hash.
        ///
        /// > Important: A recoverable signature that successfully passes `secp256k1_ecdsa_recover`
        /// > is **not guaranteed to pass** `secp256k1_ecdsa_verify` after conversion, because the
        /// > converted signature may not be in lower-S normalized form. Call
        /// > `secp256k1_ecdsa_signature_normalize` after
        /// > ``ECDSASignature/normalize`` if you need a signature that passes standard ECDSA verification.
        enum Recovery {
            /// secp256k1 ECDSA private key for producing recoverable signatures via `secp256k1_ecdsa_sign_recoverable` with RFC 6979 deterministic nonce generation.
            public struct PrivateKey: Equatable {
                /// The internal backing private key implementation.
                private let baseKey: PrivateKeyImplementation

                /// The secp256k1 public key derived from this private key.
                public var publicKey: PublicKey {
                    PublicKey(baseKey: baseKey.publicKey)
                }

                /// The raw 32-byte private key as `Data`. Keep this value confidential; disclosure allows anyone to sign on your behalf.
                public var dataRepresentation: Data {
                    baseKey.dataRepresentation
                }

                /// Creates a random secp256k1 recoverable-signing private key by generating 32 cryptographically secure random bytes validated with `secp256k1_ec_seckey_verify`.
                ///
                /// - Parameter format: The serialization format of the companion ``publicKey``; defaults to `.compressed`.
                /// - Throws: ``secp256k1Error/underlyingCryptoError`` if the generated bytes are not a valid secp256k1 private key.
                public init(format: P256K.Format = .compressed) throws {
                    self.baseKey = try PrivateKeyImplementation(format: format)
                }

                /// Creates a secp256k1 recoverable-signing private key from a 32-byte raw scalar.
                ///
                /// - Parameter data: Exactly 32 bytes; must pass `secp256k1_ec_seckey_verify`.
                /// - Parameter format: The serialization format of the companion ``publicKey``; defaults to `.compressed`.
                /// - Throws: ``secp256k1Error/incorrectKeySize`` if `data` is not 32 bytes; ``secp256k1Error/underlyingCryptoError`` if the scalar is invalid.
                public init<D: ContiguousBytes>(dataRepresentation data: D, format: P256K.Format = .compressed) throws {
                    self.baseKey = try PrivateKeyImplementation(dataRepresentation: data, format: format)
                }

                /// Returns `true` if both keys have identical 32-byte secret scalars.
                ///
                /// - Parameters:
                ///   - lhs: The left-hand side private key.
                ///   - rhs: The right-hand side private key.
                /// - Returns: `true` if the secret scalars are equal, `false` otherwise.
                public static func == (lhs: Self, rhs: Self) -> Bool {
                    lhs.baseKey.key == rhs.baseKey.key
                }
            }

            /// secp256k1 public key recovered from an ``ECDSASignature`` via `secp256k1_ecdsa_recover`, identifying the signer without prior knowledge of their public key.
            public struct PublicKey {
                /// The internal backing public key implementation.
                let baseKey: PublicKeyImplementation

                /// The serialized public key bytes as `Data`, in the key's format.
                public var dataRepresentation: Data {
                    baseKey.dataRepresentation
                }

                /// Recovers the signer's public key from a message and its ``ECDSASignature`` via `secp256k1_ecdsa_recover`, hashing `data` with SHA-256 first.
                ///
                /// - Parameter data: The original message; it is SHA-256 hashed before recovery.
                /// - Parameter signature: The 65-byte ``ECDSASignature`` containing the compact signature and recovery ID.
                /// - Parameter format: The serialization format of the recovered key; defaults to `.compressed`.
                public init<D: DataProtocol>(
                    _ data: D,
                    signature: P256K.Recovery.ECDSASignature,
                    format: P256K.Format = .compressed
                ) {
                    self.baseKey = PublicKeyImplementation(
                        SHA256.hash(data: data),
                        signature: signature,
                        format: format
                    )
                }

                /// Recovers the signer's public key from a pre-computed digest and its ``ECDSASignature`` via `secp256k1_ecdsa_recover`.
                ///
                /// - Parameter digest: The pre-computed message digest that was signed.
                /// - Parameter signature: The 65-byte ``ECDSASignature`` containing the compact signature and recovery ID.
                /// - Parameter format: The serialization format of the recovered key; defaults to `.compressed`.
                public init<D: Digest>(
                    _ digest: D,
                    signature: P256K.Recovery.ECDSASignature,
                    format: P256K.Format = .compressed
                ) {
                    self.baseKey = PublicKeyImplementation(digest, signature: signature, format: format)
                }

                /// Creates a recovery public key from a validated backing implementation.
                init(baseKey: PublicKeyImplementation) {
                    self.baseKey = baseKey
                }
            }
        }
    }

#endif
