//
//  ECDSA+PrivateKey.swift
//  21-DOT-DEV/swift-secp256k1
//
//  Copyright (c) 2026 Timechain Software Initiative, Inc.
//  Distributed under the MIT software license
//
//  See the accompanying file LICENSE for information
//

public import Foundation

#if canImport(libsecp256k1_zkp)
    import libsecp256k1_zkp
#elseif canImport(libsecp256k1)
    import libsecp256k1
#endif

@available(macOS 10.15, iOS 13, watchOS 6, tvOS 13, macCatalyst 13, visionOS 1.0, *)
public extension P256K.Signing {
    /// secp256k1 ECDSA private key for deterministically signing messages and producing ``ECDSASignature`` values using the secp256k1 curve.
    ///
    /// Create a key by generating fresh randomness or by deserializing an existing raw, PEM, or DER
    /// representation. The 32-byte secret scalar must pass `secp256k1_ec_seckey_verify` to be
    /// accepted. Keep `dataRepresentation` confidential; exposing it compromises all signatures
    /// produced by this key.
    ///
    /// The `format` parameter controls whether the **public** key companion is serialized as
    /// compressed (33 bytes, default) or uncompressed (65 bytes). The private key itself is always
    /// 32 bytes regardless of format.
    ///
    /// ## Signing
    ///
    /// ECDSA signing uses `secp256k1_ecdsa_sign` with RFC 6979 deterministic nonce generation.
    /// All signatures produced by this key are automatically normalized to lower-S form, which is
    /// the only form accepted by `secp256k1_ecdsa_verify`. Pass a `Digest` or raw `Data` to
    /// ``signature(for:)-2bdso``; the data overload hashes with SHA-256 before signing.
    struct PrivateKey: Equatable, Sendable {
        /// The internal backing key implementation.
        private let baseKey: PrivateKeyImplementation

        /// The raw 32-byte secret key bytes as `SecureBytes`.
        var key: SecureBytes {
            baseKey.key
        }

        /// The secp256k1 public key derived from this private key, used to verify signatures this key produces.
        public var publicKey: PublicKey {
            PublicKey(baseKey: baseKey.publicKey)
        }

        /// The raw 32-byte secret key as `Data`. Keep this value confidential; disclosure allows anyone to sign on your behalf.
        public var dataRepresentation: Data {
            baseKey.dataRepresentation
        }

        /// A new ``PrivateKey`` whose secret scalar is the additive inverse of this key modulo the secp256k1 curve order, produced by `secp256k1_ec_seckey_negate`.
        public var negation: Self {
            Self(baseKey: baseKey.negation)
        }

        /// Creates a private key from a validated backing implementation.
        init(baseKey: PrivateKeyImplementation) {
            self.baseKey = baseKey
        }

        /// Creates a random secp256k1 private key for signing by generating 32 cryptographically secure random bytes and validating them with `secp256k1_ec_seckey_verify`.
        ///
        /// - Parameter format: The serialization format of the companion ``publicKey``; defaults to `.compressed`.
        /// - Throws: ``secp256k1Error/underlyingCryptoError`` if the generated bytes do not form a valid secp256k1 private key (probability < 2⁻¹²⁸).
        public init(format: P256K.Format = .compressed) throws {
            self.baseKey = try PrivateKeyImplementation(format: format)
        }

        /// Creates a secp256k1 private key for signing from a 32-byte raw scalar.
        ///
        /// - Parameter data: Exactly 32 bytes representing the private key scalar; must pass `secp256k1_ec_seckey_verify`.
        /// - Parameter format: The serialization format of the companion ``publicKey``; defaults to `.compressed`.
        /// - Throws: ``secp256k1Error/incorrectKeySize`` if `data` is not 32 bytes; ``secp256k1Error/underlyingCryptoError`` if the scalar is invalid.
        public init<D: ContiguousBytes>(dataRepresentation data: D, format: P256K.Format = .compressed) throws {
            self.baseKey = try PrivateKeyImplementation(dataRepresentation: data, format: format)
        }

        /// Creates a secp256k1 private key for signing from a Privacy-Enhanced Mail (PEM) representation.
        ///
        /// - Parameters:
        ///   - pemRepresentation: A PEM representation of the key.
        public init(pemRepresentation: String) throws {
            let pem = try ASN1.PEMDocument(pemString: pemRepresentation)

            switch pem.type {
            case "EC PRIVATE KEY":
                let parsed = try ASN1.SEC1PrivateKey(asn1Encoded: Array(pem.derBytes))
                self = try .init(dataRepresentation: parsed.privateKey)

            case "PRIVATE KEY":
                let parsed = try ASN1.PKCS8PrivateKey(asn1Encoded: Array(pem.derBytes))
                self = try .init(dataRepresentation: parsed.privateKey.privateKey)

            default:
                throw CryptoKitASN1Error.invalidPEMDocument
            }
        }

        /// Creates a secp256k1 private key for signing from a Distinguished Encoding Rules (DER) encoded representation.
        ///
        /// - Parameters:
        ///   - derRepresentation: A DER-encoded representation of the key.
        public init<Bytes: RandomAccessCollection>(derRepresentation: Bytes) throws where Bytes.Element == UInt8 {
            let bytes = Array(derRepresentation)

            // We have to try to parse this twice because we have no information about what kind of key this is.
            // We try with PKCS#8 first, and then fall back to SEC.1.

            do {
                let key = try ASN1.PKCS8PrivateKey(asn1Encoded: bytes)
                self = try .init(dataRepresentation: key.privateKey.privateKey)
            } catch {
                let key = try ASN1.SEC1PrivateKey(asn1Encoded: bytes)
                self = try .init(dataRepresentation: key.privateKey)
            }
        }

        #if Xcode || ENABLE_UINT256
            /// Creates a secp256k1 private key for signing from a `UInt256` constant.
            ///
            /// - Parameter staticInt: A `UInt256` value whose raw bytes form the 32-byte private key scalar.
            /// - Parameter format: The serialization format of the companion ``publicKey``; defaults to `.compressed`.
            /// - Throws: ``secp256k1Error/underlyingCryptoError`` if the scalar is not a valid secp256k1 private key.
            @available(macOS 15.0, iOS 18.0, macCatalyst 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
            public init(_ staticInt: UInt256, format: P256K.Format = .compressed) throws {
                self.baseKey = try PrivateKeyImplementation(dataRepresentation: staticInt.rawValue, format: format)
            }
        #endif

        /// Returns `true` if both private keys have identical 32-byte secret scalars; compares using `SecureBytes` constant-time equality.
        ///
        /// - Parameters:
        ///   - lhs: The left-hand side private key.
        ///   - rhs: The right-hand side private key.
        /// - Returns: `true` if the private keys are equal, `false` otherwise.
        public static func == (lhs: Self, rhs: Self) -> Bool {
            lhs.key == rhs.key
        }
    }
}
