//
//  Schnorr+PrivateKey.swift
//  21-DOT-DEV/swift-secp256k1
//
//  Copyright (c) 2026 Timechain Software Initiative, Inc.
//  Distributed under the MIT software license
//
//  See the accompanying file LICENSE for information
//

public import Foundation

#if canImport(libsecp256k1_zkp)
    import libsecp256k1_zkp
#elseif canImport(libsecp256k1)
    import libsecp256k1
#endif

#if Xcode || ENABLE_MODULE_SCHNORRSIG

    @available(macOS 10.15, iOS 13, watchOS 6, tvOS 13, macCatalyst 13, visionOS 1.0, *)
    public extension P256K.Schnorr {
        /// secp256k1 BIP-340 Schnorr private key for signing messages with ``SchnorrSignature`` and for deriving the x-only public key used in verification.
        ///
        /// Schnorr signatures use `secp256k1_schnorrsig_sign_custom` with the BIP-340 nonce function
        /// (`secp256k1_nonce_function_bip340`). Unlike ECDSA, signing takes a 32-byte auxiliary
        /// randomness input that is mixed into the nonce for protection against fault attacks;
        /// the default ``signature(for:)-7p2ne`` overload supplies fresh random bytes automatically.
        ///
        /// Verification uses x-only public keys (``xonly``), not full compressed keys. The
        /// ``publicKey`` property returns the full ``PublicKey`` for contexts that require it.
        struct PrivateKey: Equatable {
            /// The internal backing key implementation.
            private let baseKey: PrivateKeyImplementation

            /// The raw 32-byte secret key bytes as `SecureBytes`.
            var key: SecureBytes {
                baseKey.key
            }

            /// The full secp256k1 public key derived from this private key, in uncompressed form (65 bytes).
            public var publicKey: PublicKey {
                PublicKey(baseKey: baseKey.publicKey)
            }

            /// The 32-byte x-only public key (X coordinate only) for verifying BIP-340 Schnorr signatures created with this key.
            public var xonly: XonlyKey {
                XonlyKey(baseKey: baseKey.publicKey.xonly)
            }

            /// The raw 32-byte secret key as `Data`. Keep this value confidential; disclosure allows anyone to sign on your behalf.
            public var dataRepresentation: Data {
                baseKey.dataRepresentation
            }

            /// A new ``PrivateKey`` whose secret scalar is the additive inverse modulo the secp256k1 curve order, produced by `secp256k1_ec_seckey_negate`.
            public var negation: Self {
                Self(baseKey: baseKey.negation)
            }

            /// Creates a private key from a validated backing implementation.
            init(baseKey: PrivateKeyImplementation) {
                self.baseKey = baseKey
            }

            /// Creates a random secp256k1 Schnorr private key by generating 32 cryptographically secure random bytes validated with `secp256k1_ec_seckey_verify`.
            ///
            /// The backing key always uses the uncompressed public key format internally, as required by `secp256k1_keypair_create`.
            /// - Throws: ``secp256k1Error/underlyingCryptoError`` if the generated bytes are not a valid secp256k1 private key (probability < 2⁻¹²⁸).
            public init() throws {
                self.baseKey = try PrivateKeyImplementation(format: .uncompressed)
            }

            /// Creates a secp256k1 Schnorr private key from a 32-byte raw scalar.
            ///
            /// - Parameter data: Exactly 32 bytes representing the private key scalar; must pass `secp256k1_ec_seckey_verify`.
            /// - Throws: ``secp256k1Error/incorrectKeySize`` if `data` is not 32 bytes; ``secp256k1Error/underlyingCryptoError`` if the scalar is invalid.
            public init<D: ContiguousBytes>(dataRepresentation data: D) throws {
                self.baseKey = try PrivateKeyImplementation(dataRepresentation: data)
            }

            /// Returns `true` if both keys have identical 32-byte secret scalars.
            ///
            /// - Parameters:
            ///   - lhs: The left-hand side private key.
            ///   - rhs: The right-hand side private key.
            /// - Returns: `true` if the secret scalars are equal, `false` otherwise.
            public static func == (lhs: Self, rhs: Self) -> Bool {
                lhs.baseKey.key == rhs.baseKey.key
            }
        }
    }

#endif
